--------------------------------------------------------
--  파일이 생성됨 - 수요일-8월-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "NEWUSER11"."BOOK" 
   (	"BOOKNO" VARCHAR2(10 BYTE), 
	"BOOKNAME" VARCHAR2(40 BYTE), 
	"BOOKAUTHOR" VARCHAR2(30 BYTE), 
	"BOOKPRICE" NUMBER(8,0), 
	"BOOKDATE" DATE, 
	"BOOKSTOCK" NUMBER(3,0), 
	"PUBNO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------

  CREATE TABLE "NEWUSER11"."PUBLISHER" 
   (	"PUBNO" VARCHAR2(10 BYTE), 
	"PUBNAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into NEWUSER11.BOOK
SET DEFINE OFF;
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1001','데이터베이스 이론','홍길동',22000,to_date('2018-11-11','YYYY-MM-DD'),5,'3');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1002','자바 프로그래밍','이몽룡',25000,to_date('2020-12-12','YYYY-MM-DD'),4,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1003','인터넷프로그래밍','성춘향',30000,to_date('2019-02-10','YYYY-MM-DD'),10,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1004','안드로이드 프로그래밍','변학도',23000,to_date('2017-10-10','YYYY-MM-DD'),2,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1005','안드로이드 앱','강길동',26000,to_date('2019-01-11','YYYY-MM-DD'),5,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1006','MS SQL SERVER 2014','박지성',35000,to_date('2019-03-25','YYYY-MM-DD'),7,'3');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1007','HTML & CSS','손홍민',18000,to_date('2021-01-30','YYYY-MM-DD'),3,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1008','MFC 입문','류현진',20000,to_date('2014-12-12','YYYY-MM-DD'),5,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1009','안드로이드 게임 제작','나길동',33000,to_date('2017-10-31','YYYY-MM-DD'),5,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1010','C++객체지향 프로그래밍','추신수',24000,to_date('2018-04-20','YYYY-MM-DD'),2,'3');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1011','JSP 웹 프로그래밍','김연아',27000,to_date('2019-10-23','YYYY-MM-DD'),8,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1012','해커들의 해킹 기법','손연재',32000,to_date('2017-07-07','YYYY-MM-DD'),1,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1013','자료구조','홍길동',19000,to_date('2019-01-20','YYYY-MM-DD'),4,'1');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1014','웹 해킹과 침해사고 분석','성춘향',35000,to_date('2017-11-25','YYYY-MM-DD'),5,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('1015','자바스크립 & jQuery','홍길동',27000,to_date('2018-10-22','YYYY-MM-DD'),2,'2');
Insert into NEWUSER11.BOOK (BOOKNO,BOOKNAME,BOOKAUTHOR,BOOKPRICE,BOOKDATE,BOOKSTOCK,PUBNO) values ('12345678','booktest','test',33000,to_date('2020-01-01','YYYY-MM-DD'),5,'1');
REM INSERTING into NEWUSER11.PUBLISHER
SET DEFINE OFF;
Insert into NEWUSER11.PUBLISHER (PUBNO,PUBNAME) values ('1','서울 출판사');
Insert into NEWUSER11.PUBLISHER (PUBNO,PUBNAME) values ('2','도서출판 강남');
Insert into NEWUSER11.PUBLISHER (PUBNO,PUBNAME) values ('3','정보출판사');
--------------------------------------------------------
--  DDL for Index PK_BOOK_BOOKNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWUSER11"."PK_BOOK_BOOKNO" ON "NEWUSER11"."BOOK" ("BOOKNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PUBLISHER_PUBNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWUSER11"."PK_PUBLISHER_PUBNO" ON "NEWUSER11"."PUBLISHER" ("PUBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_BOOK_BOOKNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWUSER11"."PK_BOOK_BOOKNO" ON "NEWUSER11"."BOOK" ("BOOKNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PUBLISHER_PUBNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWUSER11"."PK_PUBLISHER_PUBNO" ON "NEWUSER11"."PUBLISHER" ("PUBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "NEWUSER11"."BOOK" ADD CONSTRAINT "PK_BOOK_BOOKNO" PRIMARY KEY ("BOOKNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------

  ALTER TABLE "NEWUSER11"."PUBLISHER" ADD CONSTRAINT "PK_PUBLISHER_PUBNO" PRIMARY KEY ("PUBNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "NEWUSER11"."BOOK" ADD CONSTRAINT "FK_BOOK_PUBLISHER" FOREIGN KEY ("PUBNO")
	  REFERENCES "NEWUSER11"."PUBLISHER" ("PUBNO") ENABLE;
